// ════════════════════════════════════════════════════════════════
//  medicine.dart  –  Blueprint for a Medicine object
//  Think of this like a "form" that every medicine entry must fill
// ════════════════════════════════════════════════════════════════

class Medicine {
  // Each field stores one piece of info about the medicine
  final String id;          // Unique ID (auto-generated by Firestore)
  final String name;        // e.g. "Paracetamol"
  final String dosage;      // e.g. "500mg"
  final String frequency;   // e.g. "Twice a day"
  final String time;        // e.g. "08:00 AM"
  final int daysLeft;       // How many days of medicine remain
  final String notes;       // Any extra info like "take after food"
  final DateTime createdAt; // When this entry was created

  // Constructor – used when creating a new Medicine object
  Medicine({
    required this.id,
    required this.name,
    required this.dosage,
    required this.frequency,
    required this.time,
    required this.daysLeft,
    this.notes = '',
    required this.createdAt,
  });

  // ── Convert Medicine → Map (to save to Firestore) ──────────
  // Firestore stores data as key-value maps, not Dart objects
  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'dosage': dosage,
      'frequency': frequency,
      'time': time,
      'daysLeft': daysLeft,
      'notes': notes,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  // ── Convert Map → Medicine (when reading from Firestore) ───
  // Factory constructors create an object from another format
  factory Medicine.fromMap(String id, Map<String, dynamic> map) {
    return Medicine(
      id: id,
      name: map['name'] ?? '',
      dosage: map['dosage'] ?? '',
      frequency: map['frequency'] ?? '',
      time: map['time'] ?? '',
      daysLeft: map['daysLeft'] ?? 0,
      notes: map['notes'] ?? '',
      createdAt: DateTime.parse(map['createdAt']),
    );
  }
}
